CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/fsr.glsl"; show-text "FSR"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/nis.glsl"; show-text "NIS"
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
